version: "3.7"
services:
  omero-web-dev:
    container_name: omero-dev
    build:
      context: ./omero-dev
    image: omero-dev
    environment:
      - ${OMEROHOST-localhost}
    volumes:
      - type: bind
        source: ${OMERO_DEV_DIR-./addons}
        target: /addons
    entrypoint: /usr/bin/bash
  